# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCc < Formula
  desc "git subcommand for generating conventional commits compliant commit messages"
  homepage "https://github.com/45413/git-cc"
  version "1.1.0"
  license "MIT"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/45413/git-cc/releases/download/v1.1.0/git-cc_Darwin_arm64.tar.gz"
      sha256 "b4d4551c26ec2696007c581c82a884e878c271e2aa7f762536514ed04a36f739"

      def install
        bin.install "git-cc"
        man1.install "share/man/git-cc.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/45413/git-cc/releases/download/v1.1.0/git-cc_Darwin_x86_64.tar.gz"
      sha256 "12b2c726ed55e21d61d37846dc5ba54e079da619f623ed95a2a8b72f4a0777c1"

      def install
        bin.install "git-cc"
        man1.install "share/man/git-cc.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/45413/git-cc/releases/download/v1.1.0/git-cc_Linux_arm64.tar.gz"
      sha256 "f7b4f04a051abae830aa550208366d6bef4bf9cae10f42f2a054f2665f76e999"

      def install
        bin.install "git-cc"
        man1.install "share/man/git-cc.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/45413/git-cc/releases/download/v1.1.0/git-cc_Linux_x86_64.tar.gz"
      sha256 "baf091ad9dfd5f04e21fafdbb5e847cb9199a811afca3b7ca2739ae18e4457b5"

      def install
        bin.install "git-cc"
        man1.install "share/man/git-cc.1.gz"
      end
    end
  end

  def caveats
    <<~EOS
      To start interactive prompt run 'git cc'
    EOS
  end

  test do
    system "#{bin}/git-cc --version"
  end
end
