# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCc < Formula
  desc "git subcommand for generating conventional commits compliant commit messages"
  homepage "https://github.com/45413/git-cc"
  version "1.1.1"
  license "MIT"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/45413/git-cc/releases/download/v1.1.1/git-cc_Darwin_arm64.tar.gz"
      sha256 "fa6438db42a4043d346583b0fdaf0f50e8f59adcacfa8c0ff42d129750e6dd7d"

      def install
        bin.install "git-cc"
        man1.install "share/man/git-cc.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/45413/git-cc/releases/download/v1.1.1/git-cc_Darwin_x86_64.tar.gz"
      sha256 "4ffd046d9ef9529b3a95c9e015ca89c30bb852b7df1dfcc9fd158b8ce5b5a4fa"

      def install
        bin.install "git-cc"
        man1.install "share/man/git-cc.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/45413/git-cc/releases/download/v1.1.1/git-cc_Linux_arm64.tar.gz"
      sha256 "ae4ff3990804484ae543059a1a1f6184bd1e7d8a028b78a4765328f7a0a68660"

      def install
        bin.install "git-cc"
        man1.install "share/man/git-cc.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/45413/git-cc/releases/download/v1.1.1/git-cc_Linux_x86_64.tar.gz"
      sha256 "f42a4a3026af7aabe79c1b02038dcfa8d00bafc3ddf0dc88a6b1167243135cd8"

      def install
        bin.install "git-cc"
        man1.install "share/man/git-cc.1.gz"
      end
    end
  end

  def caveats
    <<~EOS
      To start interactive prompt run 'git cc'
    EOS
  end

  test do
    system "#{bin}/git-cc --version"
  end
end
