# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCc < Formula
  desc "git subcommand for generating conventional commits compliant commit messages"
  homepage "https://github.com/45413/git-cc"
  version "1.0.0"
  license "MIT"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/45413/git-cc/releases/download/v1.0.0/git-cc_Darwin_arm64.tar.gz"
      sha256 "f3c684d195a1229ab97d086582c731a172b864f9e768016aa21f335b3c1ecbb9"

      def install
        bin.install "git-cc"
        man1.install "share/man/git-cc.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/45413/git-cc/releases/download/v1.0.0/git-cc_Darwin_x86_64.tar.gz"
      sha256 "3062a86539dd184805bfffde6142e9d9b12e95a921eb56541ac138bc73d84b22"

      def install
        bin.install "git-cc"
        man1.install "share/man/git-cc.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/45413/git-cc/releases/download/v1.0.0/git-cc_Linux_arm64.tar.gz"
      sha256 "24fde0fb712330a23a3f26f69b239cf87fb8264c57bd81816df6d2f0cfdd6d69"

      def install
        bin.install "git-cc"
        man1.install "share/man/git-cc.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/45413/git-cc/releases/download/v1.0.0/git-cc_Linux_x86_64.tar.gz"
      sha256 "55bf6bed58b8ab45a16eeaa8357023d9e09ca248be94fea35bccab91e62ba19d"

      def install
        bin.install "git-cc"
        man1.install "share/man/git-cc.1.gz"
      end
    end
  end

  def caveats
    <<~EOS
      To start interactive prompt run 'git cc'
    EOS
  end

  test do
    system "#{bin}/git-cc --version"
  end
end
